### PR TITLE
restructuring for MG

### PR DESCRIPTION
**Pull request by bfjia**
Restructured following guidelines available from https://www.microbiologyresearch.org/prepare-an-article

### CODE REVIEW

**Review by fmaguire — APPROVED** [review]
Looks good, going to tighten the aims a bit.  We can also submit the direct manubot pdf for this journal.

**Comment by bfjia** [comment]
cool. sounds good. we can just send out the PDF to everyone for review

**Comment by fmaguire** [comment]
Looking at microbial genomics published papers and the link you provided: the abstracts don't seem to be split into sections, and we need to add an "impact statement".  Can you take a stab at that and do another PR?

**Comment by bfjia** [comment]
Please see PR #17

**Pull request merged**
